### ISSUE TITLE
deprecated version woocommerce-paytpv.php

### ISSUE THREAD

**Issue by creps** [PAYCOMET/woocommerce#1]
We receive this error of file: woocommerce-paytpv.php

The wc_get_page_id argument is deprecated since version 2.1. The "pay" and "thanks" pages are no-longer used - an endpoint is added to the checkout instead. To get a valid link use the WC_Order::get_checkout_payment_url() or WC_Order::get_checkout_order_received_url() methods instead.

**Comment by txerragh** [comment]
Please, upgrade plugin to the last versión 4.1
